### ISSUE TITLE
CI to run the automated tests

### ISSUE THREAD

**Issue by avelino** [noverde/pequi#10]
to facilitate the review of new contributions it is important to have an environment to run the tests for new pull requests autatically

options:
- https://travis-ci.com/
- https://circleci.com/

**Comment by ecanuto** [comment]
We start to use Github actions on 6de376f68f1a39e3fd9bd7f13aac5eb51364e6fa. Test/Vet/Lint/Fmt/Coverage on d86571383f6119c228eeecc0d2a2639fe9df5412.

Also, project badges on 6a7db96cb1d311146a885215497651ca87a1998d, 2a9ada52742f23fdd8aaedcfc6a26f04b3736859 and 68098c4db5f1b603657a1275bbfe875cf955778b.

I think we can now close this issue.
