### ISSUE TITLE
Change payload struct

### ISSUE THREAD

**Issue by Patrick-Isidoro** [noverde/pequi#14]
Change payload struct from 'url' to 'long_url' required string.
Add 'domain'string to payload (not required).

Anything like used in bitly: https://dev.bitly.com/api-reference#createBitlink

**Comment by ecanuto** [comment]
URL has been renamed to long_url on f0d4ee850ae5168733ece989e7313cd0863cb70d and 0c988c55a4af75a67ad50dda284e42999170cc31.

We are not going to add domain to payload since we are not multi tenant at moment.
